[project]
name = ""
version = ""
description = ""
authors = [
    {name = "baamboo", email = "beom5236@gmail.com"},
]
dependencies = []
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

